# DE3584

*Key questions:*
- Why is Linux filesystem readonly? --> Boot drive failed from controller reset
- Why did node4's boot drive become inaccessible?
- What is causing the boot drive to fail on HPE Apollo4200 Gen9?
- How can we handle this error better, instead of making each other node recuse itself? --> Try and recuse the node where we see this error

*Questions for Scott:*
- Can we treat a read-only file system from subprocess differently?
- Are there any other approaches to handle this error more gracefully?
- How can we localize a read-only file system error to the node that's reporting it?
- [MSU-related] How can we handle this when the Tunables system finds a read-only file system?

## Looks similar to Nokia
```
2021-08-06T13:36:16.478208+00:00,6,3,cdnas02-1,qfsd[244]: (task2048) [/cluster/quorum/manager] quorum is abandoning: { id=502919e2-48ab-4ba4-a028-b7e00b140545 }, {
    local_node=node1,
    all_nodes={ node1, node2, node3, node4 },
    in_nodes={ node1, node2, node3, node4 },
    out_nodes={ },
    is_full=true,
    is_degraded=false,
    leader_node=node1,
    local_node_is_leader=true
}, leader told us to abort: node4: start error: subprocess_status_error(exit code 1): subprocess exited with exit code 1
```


## node1 syslogs

```
2021-08-06T13:36:19.192511+00:00,6,3,cdnas02-1,qfsd[244]: recused
```

*Ignored Hotplug Event:*

```
2021-08-06T14:27:00.881716+00:00,5,0,cdnas02-1,kernel:[617694.380968] sd 2:0:0:0: [sdn] Attached SCSI removable disk
2021-08-06T14:27:00.885710+00:00,5,0,cdnas02-1,kernel:[617694.384346] sd 2:0:0:1: [sdo] Attached SCSI removable disk
2021-08-06T14:27:01.245606+00:00,6,3,cdnas02-1,qfsd[26274]: (task42908672) [/netlink_uevent_hotplug_notifier] Relevant hotplug event "UdevUevent {
    properties: {
        ID_SERIAL: HP_iLO_LUN_01_Media_0_000002660A01-0:1,
        ID_PART_TABLE_TYPE: dos,
        ID_VENDOR_ID: 0424,
        ID_USB_INTERFACE_NUM: 00,
        TAGS: :systemd:,
        DEVTYPE: disk,
        USEC_INITIALIZED: 617718740288,
        ID_MODEL_ID: 4030,
        SUBSYSTEM: block,
        ID_INSTANCE: 0:1,
        net.ifnames: 0,
        ID_USB_DRIVER: usb-storage,
        ID_MODEL_ENC: LUN\x2001\x20Media\x200\x20\x20,
        ID_MODEL: LUN_01_Media_0,
        DEVNAME: /dev/sdo,
        ACTION: add,
        DEVPATH: /devices/pci0000:00/0000:00:14.0/usb4/4-3/4-3.1/4-3.1:1.0/host2/target2:0:0/2:0:0:1/block/sdo,
        ID_REVISION: 2.10,
        SEQNUM: 5440,
        DEVLINKS: /dev/disk/by-path/pci-0000:00:14.0-usb-0:3.1:1.0-scsi-0:0:0:1 /dev/disk/by-id/usb-HP_iLO_LUN_01_Media_0_000002660A01-0:1,
        ID_SERIAL_SHORT: 000002660A01,
        ID_VENDOR_ENC: HP\x20iLO\x20\x20,
        ID_BUS: usb,
        ID_USB_INTERFACES: :080650:,
        MINOR: 224,
        ID_PATH_TAG: pci-0000_00_14_0-usb-0_3_1_1_0-scsi-0_0_0_1,
        MAJOR: 8,
        ID_PATH: pci-0000:00:14.0-usb-0:3.1:1.0-scsi-0:0:0:1,
        ID_TYPE: disk,
        ID_VENDOR: HP_iLO
    }
}"
2021-08-06T14:27:01.257169+00:00,6,3,cdnas02-1,qfsd[26274]: (task42908672) [/netlink_uevent_hotplug_notifier] Relevant hotplug event "UdevUevent {
    properties: {
        ID_SERIAL_SHORT: 000002660A01,
        ID_VENDOR_ID: 0424,
        SEQNUM: 5437,
        ID_USB_INTERFACE_NUM: 00,
        net.ifnames: 0,
        DEVLINKS: /dev/disk/by-id/usb-HP_iLO_LUN_00_Media_0_000002660A01-0:0 /dev/disk/by-path/pci-0000:00:14.0-usb-0:3.1:1.0-scsi-0:0:0:0,
        DEVTYPE: disk,
        DEVNAME: /dev/sdn,
        ID_BUS: usb,
        ID_SERIAL: HP_iLO_LUN_00_Media_0_000002660A01-0:0,
        ID_INSTANCE: 0:0,
        ID_MODEL: LUN_00_Media_0,
        ACTION: add,
        ID_PART_TABLE_TYPE: dos,
        TAGS: :systemd:,
        ID_VENDOR_ENC: HP\x20iLO\x20\x20,
        ID_TYPE: disk,
        ID_VENDOR: HP_iLO,
        ID_MODEL_ID: 4030,
        ID_PATH_TAG: pci-0000_00_14_0-usb-0_3_1_1_0-scsi-0_0_0_0,
        SUBSYSTEM: block,
        ID_USB_DRIVER: usb-storage,
        USEC_INITIALIZED: 617718752263,
        ID_USB_INTERFACES: :080650:,
        ID_PATH: pci-0000:00:14.0-usb-0:3.1:1.0-scsi-0:0:0:0,
        MAJOR: 8,
        ID_PART_TABLE_UUID: 00000046,
        MINOR: 208,
        ID_MODEL_ENC: LUN\x2000\x20Media\x200\x20\x20,
        ID_REVISION: 2.10,
        DEVPATH: /devices/pci0000:00/0000:00:14.0/usb4/4-3/4-3.1/4-3.1:1.0/host2/target2:0:0/2:0:0:0/block/sdn
    }
}"
2021-08-06T14:27:02.956621+00:00,6,3,cdnas02-1,qfsd[26274]: (task75336192) [/device/block_device_boss] Event ignored because no data device change detected.
2021-08-06T14:27:03.111426+00:00,6,3,cdnas02-1,qfsd[26274]: (task70568449) [/device/block_device_boss] Event ignored because no data device change detected.
2021-08-06T14:27:26.925717+00:00,6,0,cdnas02-1,kernel:[617720.422249] usb 4-3.1: USB disconnect, device number 3
2021-08-06T14:27:26.937357+00:00,3,3,cdnas02-1,systemd-udevd[19000]: inotify_add_watch(9, /dev/sdn, 10) failed: No such file or directory
2021-08-06T14:27:26.938983+00:00,6,3,cdnas02-1,qfsd[26274]: (task42908672) [/netlink_uevent_hotplug_notifier] Relevant hotplug event "UdevUevent {
    properties: {
        SEQNUM: 5453,
        ID_BUS: scsi,
        ID_PATH_TAG: pci-0000_00_14_0-usb-0_3_1,
        DEVLINKS: /dev/disk/by-path/pci-0000:00:14.0-usb-0:3.1,
        ACTION: remove,
        DEVTYPE: disk,
        MINOR: 208,
        USEC_INITIALIZED: 617718752263,
        SUBSYSTEM: block,
        TAGS: :systemd:,
        net.ifnames: 0,
        MAJOR: 8,
        ID_SCSI: 1,
        DEVNAME: /dev/sdn,
        ID_PATH: pci-0000:00:14.0-usb-0:3.1,
        DEVPATH: /devices/pci0000:00/0000:00:14.0/usb4/4-3/4-3.1/4-3.1:1.0/host2/target2:0:0/2:0:0:0/block/sdn
    }
}"
2021-08-06T14:27:27.027958+00:00,6,3,cdnas02-1,qfsd[26274]: (task42908672) [/netlink_uevent_hotplug_notifier] Relevant hotplug event "UdevUevent {
    properties: {
        TAGS: :systemd:,
        ID_PATH_TAG: pci-0000_00_14_0-usb-0_3_1-scsi-0_0_0_1,
        DEVPATH: /devices/pci0000:00/0000:00:14.0/usb4/4-3/4-3.1/4-3.1:1.0/host2/target2:0:0/2:0:0:1/block/sdo,
        MINOR: 224,
        DEVNAME: /dev/sdo,
        ACTION: remove,
        SEQNUM: 5463,
        ID_PATH: pci-0000:00:14.0-usb-0:3.1-scsi-0:0:0:1,
        DEVLINKS: /dev/disk/by-path/pci-0000:00:14.0-usb-0:3.1-scsi-0:0:0:1,
        SUBSYSTEM: block,
        DEVTYPE: disk,
        USEC_INITIALIZED: 617718740288,
        MAJOR: 8,
        net.ifnames: 0
    }
}"
2021-08-06T14:27:28.741505+00:00,6,3,cdnas02-1,qfsd[26274]: (task76625152) [/device/block_device_boss] Event ignored because no data device change detected.
2021-08-06T14:27:28.851360+00:00,6,3,cdnas02-1,qfsd[26274]: (task76629760) [/device/block_device_boss] Event ignored because no data device change detected.
```

*Readonly log*
2021-08-06T13:30:55.430313+00:00,6,3,cdnas02-1,qfsd[244]: OSError: [Errno 30] Read-only file system: '/var/log/qumulo/qumulo-devices.log'

First occurence:
```
2021-08-06T13:30:20.037580+00:00,6,3,cdnas02-1,qfsd[244]: (task2048) [/cluster/quorum/manager] quorum is abandoning: { id=dad0d73d-2401-4c03-813a-7a459d7a858d }, { local_node=node1, all_nodes={ node1, node2, node3, node4 }, in_nodes={ node1, node2, node3, node4 }, out_nodes={ }, is_full=true, is_degraded=false, leader_node=node1, local_node_is_leader=true }, leader told us to abort: node4: start error: subprocess_status_error(exit code 1): subprocess exited with exit code 1
2021-08-06T13:30:20.037719+00:00,6,3,cdnas02-1,qfsd[244]: argv=[ /opt/qumulo/qinternal/device/devices.py, --get-hotplug-notifier-info ]
2021-08-06T13:30:20.037774+00:00,6,3,cdnas02-1,qfsd[244]: stdout=
2021-08-06T13:30:20.037829+00:00,6,3,cdnas02-1,qfsd[244]: stderr=Traceback (most recent call last):
2021-08-06T13:30:20.037879+00:00,6,3,cdnas02-1,qfsd[244]:   File "/opt/qumulo/qinternal/device/devices.py", line 296, in <module>
2021-08-06T13:30:20.037938+00:00,6,3,cdnas02-1,qfsd[244]:     sys.exit(main())
2021-08-06T13:30:20.037985+00:00,6,3,cdnas02-1,qfsd[244]:   File "/opt/qumulo/qinternal/core/process.py", line 272, in wrapped_f
2021-08-06T13:30:20.038031+00:00,6,3,cdnas02-1,qfsd[244]:     return f(*args, **kwargs)
2021-08-06T13:30:20.038081+00:00,6,3,cdnas02-1,qfsd[244]:   File "/opt/qumulo/qinternal/device/devices.py", line 192, in main
2021-08-06T13:30:20.038130+00:00,6,3,cdnas02-1,qfsd[244]:     format='%(asctime)s %(levelname)s [%(process)d, %(thread)d]: %(message)s',
2021-08-06T13:30:20.038176+00:00,6,3,cdnas02-1,qfsd[244]:   File "/opt/qumulo/qinternal/log/set_up.py", line 66, in set_up_logging
2021-08-06T13:30:20.038219+00:00,6,3,cdnas02-1,qfsd[244]:   File "/usr/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
2021-08-06T13:30:20.038265+00:00,6,3,cdnas02-1,qfsd[244]:   File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
2021-08-06T13:30:20.038315+00:00,6,3,cdnas02-1,qfsd[244]:   File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
2021-08-06T13:30:20.038362+00:00,6,3,cdnas02-1,qfsd[244]: OSError: [Errno 30] Read-only file system: '/var/log/qumulo/qumulo-devices.log'
```

## node2
```
2021-08-06T13:36:16.483529+00:00,6,3,cdnas02-2,qfsd[244]: (task2560) [/cluster/quorum/manager] quorum is abandoning: { id=502919e2-48ab-4ba4-a028-b7e00b140545 }, { local_node=node2, all_nodes={ node1, node2, node3, node4 }, in_nodes={ node1, node2, node3, node4 }, out_nodes={ }, is_full=true, is_degraded=false, leader_node=node1, local_node_is_leader=false }, leader told us to abort: node4: start error: subprocess_status_error(exit code 1): subprocess exited with exit code 1
2021-08-06T13:36:16.483650+00:00,6,3,cdnas02-2,qfsd[244]: argv=[ /opt/qumulo/qinternal/device/devices.py, --get-hotplug-notifier-info ]
2021-08-06T13:36:16.483709+00:00,6,3,cdnas02-2,qfsd[244]: stdout=
2021-08-06T13:36:16.483800+00:00,6,3,cdnas02-2,qfsd[244]: stderr=Traceback (most recent call last):
2021-08-06T13:36:16.483846+00:00,6,3,cdnas02-2,qfsd[244]:   File "/opt/qumulo/qinternal/device/devices.py", line 296, in <module>
2021-08-06T13:36:16.483891+00:00,6,3,cdnas02-2,qfsd[244]:     sys.exit(main())
2021-08-06T13:36:16.483935+00:00,6,3,cdnas02-2,qfsd[244]:   File "/opt/qumulo/qinternal/core/process.py", line 272, in wrapped_f
2021-08-06T13:36:16.483979+00:00,6,3,cdnas02-2,qfsd[244]:     return f(*args, **kwargs)
2021-08-06T13:36:16.484024+00:00,6,3,cdnas02-2,qfsd[244]:   File "/opt/qumulo/qinternal/device/devices.py", line 192, in main
2021-08-06T13:36:16.484067+00:00,6,3,cdnas02-2,qfsd[244]:     format='%(asctime)s %(levelname)s [%(process)d, %(thread)d]: %(message)s',
2021-08-06T13:36:16.484112+00:00,6,3,cdnas02-2,qfsd[244]:   File "/opt/qumulo/qinternal/log/set_up.py", line 66, in set_up_logging
2021-08-06T13:36:16.484156+00:00,6,3,cdnas02-2,qfsd[244]:   File "/usr/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
2021-08-06T13:36:16.484205+00:00,6,3,cdnas02-2,qfsd[244]:   File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
2021-08-06T13:36:16.484249+00:00,6,3,cdnas02-2,qfsd[244]:   File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
2021-08-06T13:36:16.484293+00:00,6,3,cdnas02-2,qfsd[244]: OSError: [Errno 30] Read-only file system: '/var/log/qumulo/qumulo-devices.log'
```

# DE3582

*Strange error messages:*
```
2021-08-06T12:38:25.852446+00:00,6,0,QF2-Archive1-4,kernel:[  166.886366] sd 0:1:0:0: [sda] tag#12 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
2021-08-06T12:38:25.852472+00:00,6,0,QF2-Archive1-4,kernel:[  166.886384] sd 0:1:0:0: [sda] tag#12 Sense Key : Medium Error [current]
2021-08-06T12:38:25.852475+00:00,6,0,QF2-Archive1-4,kernel:[  166.886388] sd 0:1:0:0: [sda] tag#12 Add. Sense: No additional sense information
2021-08-06T12:38:25.852476+00:00,6,0,QF2-Archive1-4,kernel:[  166.886394] sd 0:1:0:0: [sda] tag#12 CDB: Write Same(10) 41 00 01 09 e7 60 00 00 08 00
2021-08-06T12:38:25.852478+00:00,3,0,QF2-Archive1-4,kernel:[  166.886398] print_req_error: I/O error, dev sda, sector 17426272
2021-08-06T12:38:29.586719+00:00,6,3,qkiosk,qfsd[587]: (task11887361) [/protocols/nfs/nsm_adapter] Addresses of node id node4: { 35.12.21.55, 35.12.21.67, 35.12.21.61, 35.12.21.5 }
2021-08-06T12:38:49.597944+00:00,6,3,qkiosk,qfsd[587]: (task1750797) [/protocols/nfs/nsm_adapter] Addresses of node id node4: { 35.12.21.67, 35.12.21.5, 35.12.21.55, 35.12.21.61 }
2021-08-06T12:39:19.599169+00:00,6,3,qkiosk,qfsd[587]: (task13108995) [/protocols/nfs/nsm_adapter] Addresses of node id node4: { 35.12.21.55, 35.12.21.5, 35.12.21.61, 35.12.21.67 }
2021-08-06T12:39:27.291033+00:00,6,0,QF2-Archive1-4,kernel:[  228.328367] sd 0:1:0:0: [sda] tag#4 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
2021-08-06T12:39:27.291056+00:00,6,0,QF2-Archive1-4,kernel:[  228.328385] sd 0:1:0:0: [sda] tag#4 Sense Key : Medium Error [current]
2021-08-06T12:39:27.291064+00:00,6,0,QF2-Archive1-4,kernel:[  228.328390] sd 0:1:0:0: [sda] tag#4 Add. Sense: No additional sense information
2021-08-06T12:39:27.291085+00:00,6,0,QF2-Archive1-4,kernel:[  228.328394] sd 0:1:0:0: [sda] tag#4 CDB: Write Same(10) 41 00 01 09 eb 80 00 00 08 00
2021-08-06T12:39:27.291091+00:00,3,0,QF2-Archive1-4,kernel:[  228.328399] print_req_error: I/O error, dev sda, sector 17427328
```

## Looks like a boot drive issue again

Note: "end_reason": "leader told us to abort: node4: block_device_error: Device in slot 27 got error.",
Slot 27 contains the boot drive


```
{
    "uuid": "1675e185-ead1-412d-9f84-88fa956e14fc",
    "event_time": "2021-08-06T09:18:43.75617553Z",
    "event_name": "quorum_abandon_event",
    "release": "Qumulo Core 4.2.0",
    "build_name": "209156.1.8",
    "hw_model": "HPE288TE",
    "data": {
        "quorum_end_time": "2021-08-06T09:18:43.756165288Z",
        "end_reason": "leader told us to abort: node4: block_device_error: Device in slot 27 got error.: [ real_disk_manager_handle_disk_error_cb at disk/manager.c:180 ]",
        "quorum_uptime": 39914.870916325002,
        "current_quorum_id": {"id": "1dec5eb1-0e3d-42ed-9659-9eafe67569e5"},
        "total_nodes": 6,
        "missing_nodes": []
    }
}
{
    "uuid": "e967ea91-fc62-4929-83a9-73689d8a4d9f",
    "event_time": "2021-08-06T12:32:52.011057235Z",
    "event_name": "quorum_success_event",
    "release": "Qumulo Core 4.2.0",
    "build_name": "209156.1.8",
    "hw_model": "HPE288TE",
    "data": {
        "quorum_success_time": "2021-08-06T12:32:52.011050971Z",
        "quorum_downtime": 11648.254885683,
        "quorum_formation_time": 28.325182908999999,
        "current_quorum_id": {"id": "93261ebe-f765-4cc9-9bf4-e0e428b4c690"},
        "total_nodes": 6,
        "missing_nodes": [4]
    }
}
{
    "uuid": "939a7cfc-45ff-4563-8d56-526c06637b23",
    "event_time": "2021-08-06T12:36:23.918840807Z",
    "event_name": "quorum_abandon_event",
    "release": "Qumulo Core 4.2.0",
    "build_name": "209156.1.8",
    "hw_model": "HPE288TE",
    "data": {
        "quorum_end_time": "2021-08-06T12:36:23.918834768Z",
        "end_reason": "leader told us to abort: Found a better quorum { node1, node2, node3, node4, node5, node6 } with cluster state { all_nodes={ node1, node2, node3, node4, node5, node6 }, nq_nodes={ node4 }, prepared_nodes={ node1, node2, node3, node5, node6 }, connection_map={ node1: { node1, node2, node3, node4, node5, node6 }, node2: { node1, node2, node3, node4, node5, node6 }, node3: { node1, node2, node3, node4, node5, node6 }, node4: { node1, node2, node3, node4, node5, node6 }, node5: { node1, node2, node3, node4, node5, node6 }, node6: { node1, node2, node3, node4, node5, node6 } }, old_quorum_ids={ node1: { id=20c68017-1f10-47fd-b5d7-e398de76f3a4 }, node2: { id=20c68017-1f10-47fd-b5d7-e398de76f3a4 }, node3: { id=20c68017-1f10-47fd-b5d7-e398de76f3a4 }, node5: { id=20c68017-1f10-47fd-b5d7-e398de76f3a4 }, node6: { id=20c68017-1f10-47fd-b5d7-e398de76f3a4 } }, failures=1 }",
        "quorum_uptime": 211.90778379700001,
        "current_quorum_id": {"id": "93261ebe-f765-4cc9-9bf4-e0e428b4c690"},
        "total_nodes": 6,
        "missing_nodes": [4]
    }
}
{
    "uuid": "9d57b1ee-1467-411c-b588-bd7e76b7c765",
    "event_time": "2021-08-06T12:38:07.531641187Z",
    "event_name": "quorum_success_event",
    "release": "Qumulo Core 4.2.0",
    "build_name": "209156.1.8",
    "hw_model": "HPE288TE",
    "data": {
        "quorum_success_time": "2021-08-06T12:38:07.531636041Z",
        "quorum_downtime": 103.612801273,
        "quorum_formation_time": 57.906595777,
        "current_quorum_id": {"id": "f56055c3-c919-45e0-b7eb-728aa1684696"},
        "total_nodes": 6,
        "missing_nodes": []
    }
}
```
